export const KAIWEN_STICKERS: string[] = [
    "CAACAgUAAxkBAAMOaLbac603779KqQnWqXxt8ayuNWkAAk4XAAIfqKlVssjt2W2w46k2BA",
    "CAACAgUAAxkBAAMNaLbab-YsXmEuLd97eynP5wsDSoQAAtwZAAL2LrBVM-ww6jHuwyM2BA",
    "CAACAgUAAxkBAAMMaLbaawrmv9nGZmuR4OLlwg6N1wkAAicbAAJDULBVgTkuiqwRF742BA",
    "CAACAgUAAxkBAAMLaLbaZ_DkhWzt6mX4aHsI5SNCxxgAAnkcAAJbYqlV2R4OLkl2Edw2BA",
    "CAACAgUAAxkBAAMKaLbaYjAVt7kP1IqBi8KaF49uxPMAArwWAAJ3FqhV6lfi9-C4Db42BA",
    "CAACAgUAAxkBAAMJaLbaXWT8P7HDNgLwIp82Y7sPyd4AAsQcAALdV6hVz5cgwPgg5ls2BA",
    "CAACAgUAAxkBAAMIaLbaTO7AX-gxFnTRtt9qKWdpqKYAAvMXAAIFRIBVcpUNAUmHRl42BA",
]